/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=MigrationWorkerBindings` (hash: e32eef4a56dd51c4fdb19b461ee23225)
interface __BaseEnv_MigrationWorkerBindings {
	MIGRATION_DATABASE: Hyperdrive;
	EXPECTED_DATABASE: string;
	EXPECTED_ROLE: string;
	MIGRATION_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_MigrationWorkerBindings {}
}
interface MigrationWorkerBindings extends __BaseEnv_MigrationWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EXPECTED_DATABASE" | "EXPECTED_ROLE" | "MIGRATION_TOKEN">> {}
}
