"""add_course_class_campus_time_location

Revision ID: 1fe0cfdf2b89
Revises: 865476d3e053
Create Date: 2026-03-31 23:52:02.160952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe0cfdf2b89'
down_revision: Union[str, None] = '865476d3e053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('class_number', sa.String(length=20), nullable=True))
    op.add_column('courses', sa.Column('campus', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('time_location', sa.String(length=200), nullable=True))
    op.drop_constraint('uq_course_teacher_semester', 'courses', type_='unique')
    op.create_index('ix_course_name', 'courses', ['name'], unique=False)
    op.create_unique_constraint('uq_course_teacher_semester_class', 'courses', ['course_code', 'teacher', 'semester', 'class_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_course_teacher_semester_class', 'courses', type_='unique')
    op.drop_index('ix_course_name', table_name='courses')
    op.create_unique_constraint('uq_course_teacher_semester', 'courses', ['course_code', 'teacher', 'semester'])
    op.drop_column('courses', 'time_location')
    op.drop_column('courses', 'campus')
    op.drop_column('courses', 'class_number')
    # ### end Alembic commands ###
