"""add avatar_color to users

Revision ID: da4def77c19f
Revises: deeea2b84d98
Create Date: 2026-03-31 17:11:53.042261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4def77c19f'
down_revision: Union[str, None] = 'deeea2b84d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_color')
    # ### end Alembic commands ###
