// Generated by scripts/generate-migration-bundle.mjs. Do not edit manually.
import type { MigrationDefinition } from './migrate.js';

export const migrationBundle = [
  {
    "tag": "0000_wise_shotgun",
    "folderMillis": 1784457059992,
    "hash": "2b6c9eb749a7ed3404dfb5d8413a33430666428b777f658ec22b13b57d67a9a7",
    "statements": [
      "CREATE TYPE \"public\".\"auth_challenge_status\" AS ENUM('pending', 'active', 'consumed', 'expired');",
      "\nCREATE TYPE \"public\".\"user_role\" AS ENUM('maintainer');",
      "\nCREATE TYPE \"public\".\"user_status\" AS ENUM('active', 'suspended', 'deleted');",
      "\nCREATE TYPE \"public\".\"term_status_override\" AS ENUM('active', 'archived');",
      "\nCREATE TYPE \"public\".\"catalog_import_status\" AS ENUM('planned', 'applied', 'failed');",
      "\nCREATE TYPE \"public\".\"comment_state\" AS ENUM('visible', 'hidden');",
      "\nCREATE TYPE \"public\".\"moderation_action_type\" AS ENUM('hide', 'restore', 'suspend', 'unsuspend');",
      "\nCREATE TYPE \"public\".\"report_reason\" AS ENUM('inaccurate', 'spam', 'abuse', 'privacy', 'other');",
      "\nCREATE TYPE \"public\".\"report_status\" AS ENUM('open', 'resolved', 'dismissed');",
      "\nCREATE TYPE \"public\".\"report_target_type\" AS ENUM('course_task', 'proposal', 'comment', 'user');",
      "\nCREATE TYPE \"public\".\"personal_task_state\" AS ENUM('pending', 'completed', 'ignored');",
      "\nCREATE TYPE \"public\".\"course_task_state\" AS ENUM('visible', 'hidden', 'merged');",
      "\nCREATE TYPE \"public\".\"proposal_state\" AS ENUM('visible', 'hidden', 'redirected');",
      "\nCREATE TYPE \"public\".\"vote_direction\" AS ENUM('up', 'down');",
      "\nCREATE TYPE \"public\".\"operation_receipt_status\" AS ENUM('applied', 'rejected', 'dependency_failed');",
      "\nCREATE TYPE \"public\".\"sync_event_scope\" AS ENUM('private_user', 'class_section_public', 'authenticated_global', 'maintainer_private');",
      "\nCREATE TABLE \"auth_challenges\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"provider\" text NOT NULL,\n\t\"normalized_subject\" text NOT NULL,\n\t\"subject_display\" text NOT NULL,\n\t\"code_hmac\" text NOT NULL,\n\t\"status\" \"auth_challenge_status\" DEFAULT 'pending' NOT NULL,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"send_attempted_at\" timestamp with time zone,\n\t\"sent_at\" timestamp with time zone,\n\t\"activated_at\" timestamp with time zone,\n\t\"consumed_at\" timestamp with time zone,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"auth_challenges_attempts_nonnegative\" CHECK (\"auth_challenges\".\"attempts\" >= 0)\n);\n",
      "\nCREATE TABLE \"institutional_identities\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"provider\" text NOT NULL,\n\t\"normalized_subject\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"sessions\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"token_hash\" text NOT NULL,\n\t\"device_name\" text,\n\t\"device_metadata\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"last_seen_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"idle_expires_at\" timestamp with time zone NOT NULL,\n\t\"absolute_expires_at\" timestamp with time zone NOT NULL,\n\t\"revoked_at\" timestamp with time zone\n);\n",
      "\nCREATE TABLE \"user_roles\" (\n\t\"user_id\" uuid NOT NULL,\n\t\"role\" \"user_role\" NOT NULL,\n\t\"granted_by\" uuid,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"user_roles_user_id_role_pk\" PRIMARY KEY(\"user_id\",\"role\")\n);\n",
      "\nCREATE TABLE \"users\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"username\" text NOT NULL,\n\t\"username_key\" text NOT NULL,\n\t\"display_name\" text NOT NULL,\n\t\"avatar_url\" text,\n\t\"bio\" text,\n\t\"status\" \"user_status\" DEFAULT 'active' NOT NULL,\n\t\"profile_revision\" integer DEFAULT 1 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone,\n\tCONSTRAINT \"users_profile_revision_positive\" CHECK (\"users\".\"profile_revision\" > 0)\n);\n",
      "\nCREATE TABLE \"academic_terms\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"external_term_code\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"starts_on\" date,\n\t\"ends_on\" date,\n\t\"status_override\" \"term_status_override\",\n\t\"source_metadata\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"academic_terms_date_order\" CHECK (\"academic_terms\".\"starts_on\" is null or \"academic_terms\".\"ends_on\" is null or \"academic_terms\".\"starts_on\" <= \"academic_terms\".\"ends_on\")\n);\n",
      "\nCREATE TABLE \"class_sections\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"course_id\" uuid NOT NULL,\n\t\"external_section_id\" text NOT NULL,\n\t\"section_number\" text NOT NULL,\n\t\"instructors\" jsonb DEFAULT '[]'::jsonb NOT NULL,\n\t\"campus\" text,\n\t\"capacity\" integer,\n\t\"schedule_text\" text,\n\t\"raw_source\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"active\" boolean DEFAULT true NOT NULL,\n\t\"revision\" integer DEFAULT 1 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"class_sections_capacity_nonnegative\" CHECK (\"class_sections\".\"capacity\" is null or \"class_sections\".\"capacity\" >= 0),\n\tCONSTRAINT \"class_sections_revision_positive\" CHECK (\"class_sections\".\"revision\" > 0)\n);\n",
      "\nCREATE TABLE \"courses\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"term_id\" uuid NOT NULL,\n\t\"external_course_code\" text NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"credits\" numeric(5, 2),\n\t\"department\" text,\n\t\"source_metadata\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"catalog_imports\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"checksum\" text NOT NULL,\n\t\"filename\" text NOT NULL,\n\t\"manifest\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"row_count\" integer NOT NULL,\n\t\"diff\" jsonb NOT NULL,\n\t\"actor_id\" uuid,\n\t\"status\" \"catalog_import_status\" DEFAULT 'planned' NOT NULL,\n\t\"failure_message\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"applied_at\" timestamp with time zone\n);\n",
      "\nCREATE TABLE \"comment_revisions\" (\n\t\"comment_id\" uuid NOT NULL,\n\t\"revision\" integer NOT NULL,\n\t\"body\" text NOT NULL,\n\t\"author_id\" uuid,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"comment_revisions_comment_id_revision_pk\" PRIMARY KEY(\"comment_id\",\"revision\"),\n\tCONSTRAINT \"comment_revisions_revision_positive\" CHECK (\"comment_revisions\".\"revision\" > 0)\n);\n",
      "\nCREATE TABLE \"task_comments\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"task_id\" uuid NOT NULL,\n\t\"author_id\" uuid,\n\t\"current_revision\" integer DEFAULT 1 NOT NULL,\n\t\"state\" \"comment_state\" DEFAULT 'visible' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone,\n\tCONSTRAINT \"task_comments_current_revision_positive\" CHECK (\"task_comments\".\"current_revision\" > 0)\n);\n",
      "\nCREATE TABLE \"audit_log\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"actor_id\" uuid,\n\t\"action\" text NOT NULL,\n\t\"target_type\" text NOT NULL,\n\t\"target_id\" uuid,\n\t\"reason\" text,\n\t\"result\" jsonb DEFAULT '{}'::jsonb NOT NULL,\n\t\"request_id\" uuid NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"content_reports\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"reporter_id\" uuid NOT NULL,\n\t\"target_type\" \"report_target_type\" NOT NULL,\n\t\"target_id\" uuid NOT NULL,\n\t\"reason\" \"report_reason\" NOT NULL,\n\t\"details\" text,\n\t\"status\" \"report_status\" DEFAULT 'open' NOT NULL,\n\t\"resolution\" text,\n\t\"resolved_by\" uuid,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"resolved_at\" timestamp with time zone\n);\n",
      "\nCREATE TABLE \"moderation_actions\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"actor_id\" uuid,\n\t\"action\" \"moderation_action_type\" NOT NULL,\n\t\"target_type\" text NOT NULL,\n\t\"target_id\" uuid NOT NULL,\n\t\"reason\" text NOT NULL,\n\t\"request_id\" uuid NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);\n",
      "\nCREATE TABLE \"task_merges\" (\n\t\"source_task_id\" uuid PRIMARY KEY NOT NULL,\n\t\"target_task_id\" uuid NOT NULL,\n\t\"maintainer_id\" uuid,\n\t\"reason\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"task_merges_not_self\" CHECK (\"task_merges\".\"source_task_id\" <> \"task_merges\".\"target_task_id\")\n);\n",
      "\nCREATE TABLE \"followed_class_sections\" (\n\t\"user_id\" uuid NOT NULL,\n\t\"class_section_id\" uuid NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"followed_class_sections_user_id_class_section_id_pk\" PRIMARY KEY(\"user_id\",\"class_section_id\")\n);\n",
      "\nCREATE TABLE \"personal_task_details\" (\n\t\"user_id\" uuid NOT NULL,\n\t\"task_id\" uuid NOT NULL,\n\t\"private_title\" text,\n\t\"private_deadline\" timestamp with time zone,\n\t\"private_note\" text,\n\t\"revision\" integer DEFAULT 1 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"personal_task_details_user_id_task_id_pk\" PRIMARY KEY(\"user_id\",\"task_id\"),\n\tCONSTRAINT \"personal_task_details_revision_positive\" CHECK (\"personal_task_details\".\"revision\" > 0)\n);\n",
      "\nCREATE TABLE \"personal_task_states\" (\n\t\"user_id\" uuid NOT NULL,\n\t\"task_id\" uuid NOT NULL,\n\t\"state\" \"personal_task_state\" NOT NULL,\n\t\"revision\" integer DEFAULT 1 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"personal_task_states_user_id_task_id_pk\" PRIMARY KEY(\"user_id\",\"task_id\"),\n\tCONSTRAINT \"personal_task_states_revision_positive\" CHECK (\"personal_task_states\".\"revision\" > 0)\n);\n",
      "\nCREATE TABLE \"personal_todos\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"user_id\" uuid NOT NULL,\n\t\"class_section_id\" uuid,\n\t\"title\" text NOT NULL,\n\t\"deadline\" timestamp with time zone,\n\t\"note\" text,\n\t\"state\" \"personal_task_state\" DEFAULT 'pending' NOT NULL,\n\t\"revision\" integer DEFAULT 1 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone,\n\tCONSTRAINT \"personal_todos_revision_positive\" CHECK (\"personal_todos\".\"revision\" > 0)\n);\n",
      "\nCREATE TABLE \"accuracy_votes\" (\n\t\"user_id\" uuid NOT NULL,\n\t\"proposal_id\" uuid NOT NULL,\n\t\"direction\" \"vote_direction\" NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"accuracy_votes_user_id_proposal_id_pk\" PRIMARY KEY(\"user_id\",\"proposal_id\")\n);\n",
      "\nCREATE TABLE \"course_tasks\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"class_section_id\" uuid NOT NULL,\n\t\"created_by\" uuid,\n\t\"state\" \"course_task_state\" DEFAULT 'visible' NOT NULL,\n\t\"revision\" integer DEFAULT 1 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"course_tasks_revision_positive\" CHECK (\"course_tasks\".\"revision\" > 0)\n);\n",
      "\nCREATE TABLE \"proposal_redirects\" (\n\t\"source_proposal_id\" uuid PRIMARY KEY NOT NULL,\n\t\"canonical_proposal_id\" uuid NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"proposal_redirects_not_self\" CHECK (\"proposal_redirects\".\"source_proposal_id\" <> \"proposal_redirects\".\"canonical_proposal_id\")\n);\n",
      "\nCREATE TABLE \"proposal_vote_totals\" (\n\t\"proposal_id\" uuid PRIMARY KEY NOT NULL,\n\t\"up\" integer DEFAULT 0 NOT NULL,\n\t\"down\" integer DEFAULT 0 NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"proposal_vote_totals_up_nonnegative\" CHECK (\"proposal_vote_totals\".\"up\" >= 0),\n\tCONSTRAINT \"proposal_vote_totals_down_nonnegative\" CHECK (\"proposal_vote_totals\".\"down\" >= 0)\n);\n",
      "\nCREATE TABLE \"task_proposals\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"task_id\" uuid NOT NULL,\n\t\"author_id\" uuid,\n\t\"title\" text NOT NULL,\n\t\"deadline\" timestamp with time zone NOT NULL,\n\t\"description\" text,\n\t\"evidence_note\" text,\n\t\"evidence_url\" text,\n\t\"content_fingerprint\" text NOT NULL,\n\t\"state\" \"proposal_state\" DEFAULT 'visible' NOT NULL,\n\t\"revision\" integer DEFAULT 1 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"task_proposals_revision_positive\" CHECK (\"task_proposals\".\"revision\" > 0)\n);\n",
      "\nCREATE TABLE \"operation_receipts\" (\n\t\"user_id\" uuid NOT NULL,\n\t\"operation_id\" uuid NOT NULL,\n\t\"request_digest\" text NOT NULL,\n\t\"status\" \"operation_receipt_status\" NOT NULL,\n\t\"stable_result\" jsonb NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\tCONSTRAINT \"operation_receipts_user_id_operation_id_pk\" PRIMARY KEY(\"user_id\",\"operation_id\")\n);\n",
      "\nCREATE TABLE \"sync_events\" (\n\t\"sequence\" bigserial PRIMARY KEY NOT NULL,\n\t\"event_id\" uuid NOT NULL,\n\t\"scope\" \"sync_event_scope\" NOT NULL,\n\t\"scope_user_id\" uuid,\n\t\"class_section_id\" uuid,\n\t\"type\" text NOT NULL,\n\t\"schema_version\" integer DEFAULT 1 NOT NULL,\n\t\"payload\" jsonb NOT NULL,\n\t\"occurred_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"sync_events_schema_version_positive\" CHECK (\"sync_events\".\"schema_version\" > 0),\n\tCONSTRAINT \"sync_events_scope_target_valid\" CHECK ((\n        (\"sync_events\".\"scope\" = 'private_user' and \"sync_events\".\"scope_user_id\" is not null and \"sync_events\".\"class_section_id\" is null)\n        or (\"sync_events\".\"scope\" = 'class_section_public' and \"sync_events\".\"scope_user_id\" is null and \"sync_events\".\"class_section_id\" is not null)\n        or (\"sync_events\".\"scope\" in ('authenticated_global', 'maintainer_private') and \"sync_events\".\"scope_user_id\" is null and \"sync_events\".\"class_section_id\" is null)\n      ))\n);\n",
      "\nALTER TABLE \"institutional_identities\" ADD CONSTRAINT \"institutional_identities_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"sessions\" ADD CONSTRAINT \"sessions_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"user_roles\" ADD CONSTRAINT \"user_roles_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"user_roles\" ADD CONSTRAINT \"user_roles_granted_by_users_id_fk\" FOREIGN KEY (\"granted_by\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"class_sections\" ADD CONSTRAINT \"class_sections_course_id_courses_id_fk\" FOREIGN KEY (\"course_id\") REFERENCES \"public\".\"courses\"(\"id\") ON DELETE restrict ON UPDATE no action;",
      "\nALTER TABLE \"courses\" ADD CONSTRAINT \"courses_term_id_academic_terms_id_fk\" FOREIGN KEY (\"term_id\") REFERENCES \"public\".\"academic_terms\"(\"id\") ON DELETE restrict ON UPDATE no action;",
      "\nALTER TABLE \"catalog_imports\" ADD CONSTRAINT \"catalog_imports_actor_id_users_id_fk\" FOREIGN KEY (\"actor_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"comment_revisions\" ADD CONSTRAINT \"comment_revisions_comment_id_task_comments_id_fk\" FOREIGN KEY (\"comment_id\") REFERENCES \"public\".\"task_comments\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"comment_revisions\" ADD CONSTRAINT \"comment_revisions_author_id_users_id_fk\" FOREIGN KEY (\"author_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"task_comments\" ADD CONSTRAINT \"task_comments_task_id_course_tasks_id_fk\" FOREIGN KEY (\"task_id\") REFERENCES \"public\".\"course_tasks\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"task_comments\" ADD CONSTRAINT \"task_comments_author_id_users_id_fk\" FOREIGN KEY (\"author_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"audit_log\" ADD CONSTRAINT \"audit_log_actor_id_users_id_fk\" FOREIGN KEY (\"actor_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"content_reports\" ADD CONSTRAINT \"content_reports_reporter_id_users_id_fk\" FOREIGN KEY (\"reporter_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"content_reports\" ADD CONSTRAINT \"content_reports_resolved_by_users_id_fk\" FOREIGN KEY (\"resolved_by\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"moderation_actions\" ADD CONSTRAINT \"moderation_actions_actor_id_users_id_fk\" FOREIGN KEY (\"actor_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"task_merges\" ADD CONSTRAINT \"task_merges_source_task_id_course_tasks_id_fk\" FOREIGN KEY (\"source_task_id\") REFERENCES \"public\".\"course_tasks\"(\"id\") ON DELETE restrict ON UPDATE no action;",
      "\nALTER TABLE \"task_merges\" ADD CONSTRAINT \"task_merges_target_task_id_course_tasks_id_fk\" FOREIGN KEY (\"target_task_id\") REFERENCES \"public\".\"course_tasks\"(\"id\") ON DELETE restrict ON UPDATE no action;",
      "\nALTER TABLE \"task_merges\" ADD CONSTRAINT \"task_merges_maintainer_id_users_id_fk\" FOREIGN KEY (\"maintainer_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"followed_class_sections\" ADD CONSTRAINT \"followed_class_sections_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"followed_class_sections\" ADD CONSTRAINT \"followed_class_sections_class_section_id_class_sections_id_fk\" FOREIGN KEY (\"class_section_id\") REFERENCES \"public\".\"class_sections\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"personal_task_details\" ADD CONSTRAINT \"personal_task_details_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"personal_task_details\" ADD CONSTRAINT \"personal_task_details_task_id_course_tasks_id_fk\" FOREIGN KEY (\"task_id\") REFERENCES \"public\".\"course_tasks\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"personal_task_states\" ADD CONSTRAINT \"personal_task_states_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"personal_task_states\" ADD CONSTRAINT \"personal_task_states_task_id_course_tasks_id_fk\" FOREIGN KEY (\"task_id\") REFERENCES \"public\".\"course_tasks\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"personal_todos\" ADD CONSTRAINT \"personal_todos_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"personal_todos\" ADD CONSTRAINT \"personal_todos_class_section_id_class_sections_id_fk\" FOREIGN KEY (\"class_section_id\") REFERENCES \"public\".\"class_sections\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"accuracy_votes\" ADD CONSTRAINT \"accuracy_votes_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"accuracy_votes\" ADD CONSTRAINT \"accuracy_votes_proposal_id_task_proposals_id_fk\" FOREIGN KEY (\"proposal_id\") REFERENCES \"public\".\"task_proposals\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"course_tasks\" ADD CONSTRAINT \"course_tasks_class_section_id_class_sections_id_fk\" FOREIGN KEY (\"class_section_id\") REFERENCES \"public\".\"class_sections\"(\"id\") ON DELETE restrict ON UPDATE no action;",
      "\nALTER TABLE \"course_tasks\" ADD CONSTRAINT \"course_tasks_created_by_users_id_fk\" FOREIGN KEY (\"created_by\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"proposal_redirects\" ADD CONSTRAINT \"proposal_redirects_source_proposal_id_task_proposals_id_fk\" FOREIGN KEY (\"source_proposal_id\") REFERENCES \"public\".\"task_proposals\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"proposal_redirects\" ADD CONSTRAINT \"proposal_redirects_canonical_proposal_id_task_proposals_id_fk\" FOREIGN KEY (\"canonical_proposal_id\") REFERENCES \"public\".\"task_proposals\"(\"id\") ON DELETE restrict ON UPDATE no action;",
      "\nALTER TABLE \"proposal_vote_totals\" ADD CONSTRAINT \"proposal_vote_totals_proposal_id_task_proposals_id_fk\" FOREIGN KEY (\"proposal_id\") REFERENCES \"public\".\"task_proposals\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"task_proposals\" ADD CONSTRAINT \"task_proposals_task_id_course_tasks_id_fk\" FOREIGN KEY (\"task_id\") REFERENCES \"public\".\"course_tasks\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"task_proposals\" ADD CONSTRAINT \"task_proposals_author_id_users_id_fk\" FOREIGN KEY (\"author_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE set null ON UPDATE no action;",
      "\nALTER TABLE \"operation_receipts\" ADD CONSTRAINT \"operation_receipts_user_id_users_id_fk\" FOREIGN KEY (\"user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"sync_events\" ADD CONSTRAINT \"sync_events_scope_user_id_users_id_fk\" FOREIGN KEY (\"scope_user_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"sync_events\" ADD CONSTRAINT \"sync_events_class_section_id_class_sections_id_fk\" FOREIGN KEY (\"class_section_id\") REFERENCES \"public\".\"class_sections\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nCREATE UNIQUE INDEX \"auth_challenges_current_subject_unique\" ON \"auth_challenges\" USING btree (\"provider\",\"normalized_subject\") WHERE \"auth_challenges\".\"status\" in ('pending', 'active');",
      "\nCREATE INDEX \"auth_challenges_expiry_idx\" ON \"auth_challenges\" USING btree (\"expires_at\");",
      "\nCREATE UNIQUE INDEX \"institutional_identities_subject_unique\" ON \"institutional_identities\" USING btree (\"provider\",\"normalized_subject\");",
      "\nCREATE INDEX \"institutional_identities_user_idx\" ON \"institutional_identities\" USING btree (\"user_id\");",
      "\nCREATE UNIQUE INDEX \"sessions_token_hash_unique\" ON \"sessions\" USING btree (\"token_hash\");",
      "\nCREATE INDEX \"sessions_user_idx\" ON \"sessions\" USING btree (\"user_id\");",
      "\nCREATE INDEX \"sessions_expiry_idx\" ON \"sessions\" USING btree (\"idle_expires_at\",\"absolute_expires_at\");",
      "\nCREATE UNIQUE INDEX \"users_username_key_unique\" ON \"users\" USING btree (\"username_key\");",
      "\nCREATE UNIQUE INDEX \"academic_terms_external_code_unique\" ON \"academic_terms\" USING btree (\"external_term_code\");",
      "\nCREATE UNIQUE INDEX \"class_sections_external_id_unique\" ON \"class_sections\" USING btree (\"external_section_id\");",
      "\nCREATE INDEX \"class_sections_course_idx\" ON \"class_sections\" USING btree (\"course_id\");",
      "\nCREATE UNIQUE INDEX \"courses_term_external_code_unique\" ON \"courses\" USING btree (\"term_id\",\"external_course_code\");",
      "\nCREATE INDEX \"courses_term_idx\" ON \"courses\" USING btree (\"term_id\");",
      "\nCREATE INDEX \"catalog_imports_checksum_idx\" ON \"catalog_imports\" USING btree (\"checksum\");",
      "\nCREATE INDEX \"catalog_imports_status_created_idx\" ON \"catalog_imports\" USING btree (\"status\",\"created_at\");",
      "\nCREATE INDEX \"task_comments_task_idx\" ON \"task_comments\" USING btree (\"task_id\");",
      "\nCREATE INDEX \"audit_log_created_idx\" ON \"audit_log\" USING btree (\"created_at\");",
      "\nCREATE INDEX \"audit_log_actor_idx\" ON \"audit_log\" USING btree (\"actor_id\",\"created_at\");",
      "\nCREATE INDEX \"content_reports_status_created_idx\" ON \"content_reports\" USING btree (\"status\",\"created_at\");",
      "\nCREATE INDEX \"content_reports_target_idx\" ON \"content_reports\" USING btree (\"target_type\",\"target_id\");",
      "\nCREATE INDEX \"moderation_actions_target_idx\" ON \"moderation_actions\" USING btree (\"target_type\",\"target_id\");",
      "\nCREATE INDEX \"moderation_actions_actor_idx\" ON \"moderation_actions\" USING btree (\"actor_id\",\"created_at\");",
      "\nCREATE INDEX \"task_merges_target_idx\" ON \"task_merges\" USING btree (\"target_task_id\");",
      "\nCREATE INDEX \"personal_todos_user_idx\" ON \"personal_todos\" USING btree (\"user_id\");",
      "\nCREATE INDEX \"personal_todos_class_section_idx\" ON \"personal_todos\" USING btree (\"class_section_id\");",
      "\nCREATE INDEX \"course_tasks_class_section_idx\" ON \"course_tasks\" USING btree (\"class_section_id\");",
      "\nCREATE INDEX \"proposal_redirects_canonical_idx\" ON \"proposal_redirects\" USING btree (\"canonical_proposal_id\");",
      "\nCREATE UNIQUE INDEX \"task_proposals_task_fingerprint_unique\" ON \"task_proposals\" USING btree (\"task_id\",\"content_fingerprint\");",
      "\nCREATE INDEX \"task_proposals_task_idx\" ON \"task_proposals\" USING btree (\"task_id\");",
      "\nCREATE INDEX \"operation_receipts_expiry_idx\" ON \"operation_receipts\" USING btree (\"expires_at\");",
      "\nCREATE UNIQUE INDEX \"sync_events_event_id_unique\" ON \"sync_events\" USING btree (\"event_id\");",
      "\nCREATE INDEX \"sync_events_scope_sequence_idx\" ON \"sync_events\" USING btree (\"scope\",\"sequence\");",
      "\nCREATE INDEX \"sync_events_user_sequence_idx\" ON \"sync_events\" USING btree (\"scope_user_id\",\"sequence\");",
      "\nCREATE INDEX \"sync_events_class_sequence_idx\" ON \"sync_events\" USING btree (\"class_section_id\",\"sequence\");"
    ]
  },
  {
    "tag": "0001_good_human_robot",
    "folderMillis": 1784466438305,
    "hash": "132bcbaecb15d477b82d8cb57e84f8364413935b5ff9c53a0e6ebb4907412bea",
    "statements": [
      "CREATE TABLE \"registration_tokens\" (\n\t\"id\" uuid PRIMARY KEY NOT NULL,\n\t\"token_hash\" text NOT NULL,\n\t\"provider\" text NOT NULL,\n\t\"normalized_subject\" text NOT NULL,\n\t\"subject_display\" text NOT NULL,\n\t\"attempts\" integer DEFAULT 0 NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\t\"consumed_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"registration_tokens_attempts_nonnegative\" CHECK (\"registration_tokens\".\"attempts\" >= 0)\n);\n",
      "\nDROP INDEX \"auth_challenges_current_subject_unique\";",
      "\nCREATE UNIQUE INDEX \"registration_tokens_hash_unique\" ON \"registration_tokens\" USING btree (\"token_hash\");",
      "\nCREATE INDEX \"registration_tokens_expiry_idx\" ON \"registration_tokens\" USING btree (\"expires_at\");",
      "\nCREATE UNIQUE INDEX \"auth_challenges_active_subject_unique\" ON \"auth_challenges\" USING btree (\"provider\",\"normalized_subject\") WHERE \"auth_challenges\".\"status\" = 'active';",
      "\nCREATE UNIQUE INDEX \"auth_challenges_pending_subject_unique\" ON \"auth_challenges\" USING btree (\"provider\",\"normalized_subject\") WHERE \"auth_challenges\".\"status\" = 'pending';"
    ]
  },
  {
    "tag": "0002_lame_rocket_racer",
    "folderMillis": 1784468302677,
    "hash": "9aec3dd236f72fb610ce13daaa295c8704213b255261f3f2726721f942d74bcc",
    "statements": [
      "CREATE TABLE \"catalog_import_batches\" (\n\t\"import_id\" uuid NOT NULL,\n\t\"batch_index\" integer NOT NULL,\n\t\"batch_checksum\" text NOT NULL,\n\t\"payload\" jsonb NOT NULL,\n\t\"applied_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"catalog_import_batches_import_id_batch_index_pk\" PRIMARY KEY(\"import_id\",\"batch_index\"),\n\tCONSTRAINT \"catalog_import_batches_index_nonnegative\" CHECK (\"catalog_import_batches\".\"batch_index\" >= 0)\n);\n",
      "\nALTER TABLE \"catalog_imports\" ALTER COLUMN \"diff\" SET DEFAULT 'null'::jsonb;",
      "\nALTER TABLE \"catalog_imports\" ALTER COLUMN \"diff\" DROP NOT NULL;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"header_hash\" text;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"manifest_hash\" text;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"environment\" text DEFAULT 'unknown' NOT NULL;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"total_batches\" integer DEFAULT 1 NOT NULL;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"received_batches\" integer DEFAULT 0 NOT NULL;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"applied_batches\" integer DEFAULT 0 NOT NULL;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"baseline_hash\" text;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"deactivation_count\" integer DEFAULT 0 NOT NULL;",
      "\nALTER TABLE \"catalog_imports\" ADD COLUMN \"updated_at\" timestamp with time zone DEFAULT now() NOT NULL;",
      "\nALTER TABLE \"catalog_import_batches\" ADD CONSTRAINT \"catalog_import_batches_import_id_catalog_imports_id_fk\" FOREIGN KEY (\"import_id\") REFERENCES \"public\".\"catalog_imports\"(\"id\") ON DELETE cascade ON UPDATE no action;",
      "\nALTER TABLE \"catalog_imports\" ADD CONSTRAINT \"catalog_imports_row_count_nonnegative\" CHECK (\"catalog_imports\".\"row_count\" >= 0);",
      "\nALTER TABLE \"catalog_imports\" ADD CONSTRAINT \"catalog_imports_total_batches_positive\" CHECK (\"catalog_imports\".\"total_batches\" > 0);",
      "\nALTER TABLE \"catalog_imports\" ADD CONSTRAINT \"catalog_imports_batch_progress_valid\" CHECK (\"catalog_imports\".\"received_batches\" >= 0 and \"catalog_imports\".\"applied_batches\" >= 0 and \"catalog_imports\".\"received_batches\" <= \"catalog_imports\".\"total_batches\" and \"catalog_imports\".\"applied_batches\" <= \"catalog_imports\".\"total_batches\");",
      "\nALTER TABLE \"catalog_imports\" ADD CONSTRAINT \"catalog_imports_deactivation_count_nonnegative\" CHECK (\"catalog_imports\".\"deactivation_count\" >= 0);"
    ]
  },
  {
    "tag": "0003_redundant_shinko_yamashiro",
    "folderMillis": 1784468442508,
    "hash": "459a7c6b5ef748d556f67f4b41fcdfb70e14eeaa3ea1b8a93fa8664bc413f936",
    "statements": [
      "ALTER TABLE \"courses\" ADD COLUMN \"active\" boolean DEFAULT true NOT NULL;",
      "\nALTER TABLE \"courses\" ADD COLUMN \"revision\" integer DEFAULT 1 NOT NULL;",
      "\nALTER TABLE \"courses\" ADD CONSTRAINT \"courses_revision_positive\" CHECK (\"courses\".\"revision\" > 0);"
    ]
  },
  {
    "tag": "0004_nostalgic_thaddeus_ross",
    "folderMillis": 1784468829203,
    "hash": "da68b59877e6d1495d6232c6e37bcc829655478a6513ce0ac755910fae17e708",
    "statements": [
      "ALTER TABLE \"catalog_imports\" ADD COLUMN \"normalized_term\" jsonb DEFAULT '{}'::jsonb NOT NULL;"
    ]
  },
  {
    "tag": "0005_condemned_winter_soldier",
    "folderMillis": 1784477842784,
    "hash": "041387b0396165f087c5580d783363a6a7764822c07952bf609e0112053a47ea",
    "statements": [
      "CREATE TABLE \"sync_event_retention\" (\n\t\"singleton_id\" integer PRIMARY KEY DEFAULT 1 NOT NULL,\n\t\"minimum_sequence\" bigint DEFAULT 0 NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"sync_event_retention_singleton\" CHECK (\"sync_event_retention\".\"singleton_id\" = 1),\n\tCONSTRAINT \"sync_event_retention_sequence_nonnegative\" CHECK (\"sync_event_retention\".\"minimum_sequence\" >= 0)\n);\n"
    ]
  },
  {
    "tag": "0006_dear_jasper_sitwell",
    "folderMillis": 1784509911759,
    "hash": "5456d68b07a42cfd280f9f5ac248d1fd3971f501d23601dd7e01fea5714c184d",
    "statements": [
      "CREATE TABLE \"rate_limit_counters\" (\n\t\"scope\" text NOT NULL,\n\t\"subject_key\" text NOT NULL,\n\t\"window_start\" timestamp with time zone NOT NULL,\n\t\"count\" integer DEFAULT 1 NOT NULL,\n\t\"expires_at\" timestamp with time zone NOT NULL,\n\tCONSTRAINT \"rate_limit_counters_scope_subject_key_window_start_pk\" PRIMARY KEY(\"scope\",\"subject_key\",\"window_start\"),\n\tCONSTRAINT \"rate_limit_counters_count_positive\" CHECK (\"rate_limit_counters\".\"count\" > 0),\n\tCONSTRAINT \"rate_limit_counters_window_valid\" CHECK (\"rate_limit_counters\".\"expires_at\" > \"rate_limit_counters\".\"window_start\")\n);\n",
      "\nCREATE INDEX \"rate_limit_counters_expiry_idx\" ON \"rate_limit_counters\" USING btree (\"expires_at\");"
    ]
  },
  {
    "tag": "0007_shallow_black_knight",
    "folderMillis": 1784874175428,
    "hash": "7d5f55e7bc5d94280a211d48366b6930d85505d6e3f5453c35ec1b6f38cea1b3",
    "statements": [
      "ALTER TABLE \"class_sections\" ADD COLUMN \"department_code\" text;",
      "\nALTER TABLE \"class_sections\" ADD COLUMN \"department_name\" text;",
      "\nUPDATE \"class_sections\"\nSET\n\t\"department_code\" = nullif(btrim(\"raw_source\" ->> 'PKDWDM'), ''),\n\t\"department_name\" = nullif(btrim(\"raw_source\" ->> 'PKDWDM_DISPLAY'), '')\nWHERE\n\t\"raw_source\" ? 'PKDWDM'\n\tOR \"raw_source\" ? 'PKDWDM_DISPLAY';\n"
    ]
  },
  {
    "tag": "0008_volatile_adam_destine",
    "folderMillis": 1784874896167,
    "hash": "f9d97e605bc82537a0b8ef02871e3301253321b29f435b67ed71a84fb91b9c4b",
    "statements": [
      "ALTER TABLE \"courses\" DROP COLUMN \"department\";"
    ]
  },
  {
    "tag": "0009_overrated_photon",
    "folderMillis": 1784948641296,
    "hash": "206a37fbe5e956209cdf452cf35fb70fcb6c59e268a684b7b100c609cf53241f",
    "statements": [
      "ALTER TYPE \"public\".\"catalog_import_status\" ADD VALUE 'cancelled';",
      "\nALTER TYPE \"public\".\"catalog_import_status\" ADD VALUE 'expired';"
    ]
  },
  {
    "tag": "0010_slow_molly_hayes",
    "folderMillis": 1785063709783,
    "hash": "815465e9bb6a06dc71071046f6eee739b532457fb5528a1a66cf21d3f9ab0123",
    "statements": [
      "ALTER TYPE \"public\".\"vote_direction\" ADD VALUE 'none';",
      "\nALTER TABLE \"accuracy_votes\" ADD COLUMN \"revision\" integer DEFAULT 1 NOT NULL;",
      "\nALTER TABLE \"proposal_vote_totals\" ADD COLUMN \"revision\" integer DEFAULT 1 NOT NULL;",
      "\nALTER TABLE \"accuracy_votes\" ADD CONSTRAINT \"accuracy_votes_revision_positive\" CHECK (\"accuracy_votes\".\"revision\" > 0);",
      "\nALTER TABLE \"proposal_vote_totals\" ADD CONSTRAINT \"proposal_vote_totals_revision_positive\" CHECK (\"proposal_vote_totals\".\"revision\" > 0);"
    ]
  },
  {
    "tag": "0011_hot_red_skull",
    "folderMillis": 1785072235122,
    "hash": "7513f5b0a83a91a4527dceae2b5e9a7e2365b490140754628ec64fea4b068ecc",
    "statements": [
      "CREATE TABLE \"catalog_revision\" (\n\t\"singleton_id\" integer PRIMARY KEY DEFAULT 1 NOT NULL,\n\t\"revision\" integer DEFAULT 1 NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\tCONSTRAINT \"catalog_revision_singleton\" CHECK (\"catalog_revision\".\"singleton_id\" = 1),\n\tCONSTRAINT \"catalog_revision_positive\" CHECK (\"catalog_revision\".\"revision\" > 0)\n);",
      "\nINSERT INTO \"catalog_revision\" (\"singleton_id\", \"revision\") VALUES (1, 1);\n"
    ]
  }
] as const satisfies readonly MigrationDefinition[];
